var words = ["ABA","ABAD","ABADI","ABAH","ABAI","ABAL","ABANG","ABANGAN","ABDI","ABDIKASI","ABDOMEN","ABDOMINAL","ABDUKSI","ABDUKTOR","ABERASI","ABIOTIK","ABIS","ABJAD","MADU","IDE"];

exports.words = words;
